### ISSUE TITLE
how you make this?

### ISSUE THREAD

**Issue by Henrique-Rb-Dev** [1Leep/sexo-language#2]
how it works?

**Comment by Henrique-Rb-Dev** [comment]
what used?

**Comment by Henrique-Rb-Dev** [comment]
what is it for?

**Comment by 1Leep** [comment]
> 

this is an interpreter, used to read the input of the written codes using their own syntax and convert so that another language can run the commands.

the information is in the repository's Readme.

**Comment by Henrique-Rb-Dev** [comment]
legal
